name = "bella"
version = "0.1.0"
description = "A simple functional programming language"
target = "javascript"
licences = ["MIT"]
repository = { type = "github", user = "MystPi", repo = "bella" }

[dependencies]
gleam_stdlib = "~> 0.29"
hug = "~> 0.1"
gleam_community_ansi = "~> 1.1"

[javascript]
runtime = "node"

[javascript.deno]
allow_all = true
