name = "bella"
version = "0.1.0"
description = "A simple functional programming language"
target = "javascript"
licences = ["MIT"]
repository = { type = "github", user = "MystPi", repo = "bella" }

[dependencies]
gleam_stdlib = "~> 0.29"